### ISSUE TITLE
Intermittent rendering problems

### ISSUE THREAD

**Issue by ababo** [fyne-io/fyne#1207]
We have an application with a header strip of icons that indicate a progress (a wizard like window with step pages). Technically the header consists of a horizontal box with images (of a same size) inside. Depending on active page we dynamically replace some images to indicate a progress (`box.Children[i]=newImage` and then `box.Refresh()`).

The problem is that sometimes some images are not drawn looking disappeared (see the attached image). This is an intermittent problem.

We have another problem as well (also appearing on the attached screenshot). The text content of a step page sometimes looks deformed/squashed for 1-3 seconds before being laid out properly.

![image](https://user-images.githubusercontent.com/503292/88378327-112fde80-cda1-11ea-9e34-10ad1f1a4a95.png)

Fyne: 5cfe49a
OS: Multiple versions of OSX and Windows
Golang: 1.14

**Comment by ababo** [comment]
Another screenshot related to the header problem.

![image](https://user-images.githubusercontent.com/503292/88378565-90bdad80-cda1-11ea-9580-505435fb3fc0.png)

**Comment by andydotxyz** [comment]
In the header images are they always being replaced or are they sometimes being hidden?
When the layout is incorrect does resizing correct it?

Can you share more information about the code for the text layout?

**Comment by ababo** [comment]
> In the header images are they always being replaced or are they sometimes being hidden?

Currently we hide some icons, but the problem was reproduced before as well, when we didn't hide them.

> When the layout is incorrect does resizing correct it?

Yes.

**Comment by andydotxyz** [comment]
Oh, I thought from your previous descriptions that the issue was a space being left - but the issue is with the icon remaining hidden?
What were the symptoms before the hiding of icons was added?

Would it be possible to share some code that replicates this issue and the exact step sthat we would follow to replicate?
Thanks

**Comment by ababo** [comment]
> What were the symptoms before the hiding of icons was added?

Exactly the same symptoms. When the header is updated (an active page image is replaced with another) sometimes some image (this one or another) is disappeared. If I resize the window the missing image appears back.

**Comment by ababo** [comment]
Here is the code:
```go
type header struct {
	fyne.Widget
	pages         []*page
	box           *widget.Box
	activeItems   []*canvas.Image
	inactiveItems []*canvas.Image
	activeIndex   int
}

func appendHeaderImage(imgs *[]*canvas.Image, path string) {
	img := createImage(path)
	img.FillMode = canvas.ImageFillStretch
	img.SetMinSize(fyne.Size{headerItemWidth, headerItemHeight})
	*imgs = append(*imgs, img)
}

func newHeader(pages []*page) *header {
	var active []*canvas.Image
	var inactive []*canvas.Image

	for _, page := range pages {
		appendHeaderImage(&active, page.activeHeaderImage)
		appendHeaderImage(&inactive, page.inactiveHeaderImage)
	}

	hbox := widget.NewHBox(make([]fyne.CanvasObject, len(pages))...)
	vbox := widget.NewVBox(
		&backgroundColorWrapper{hbox, headerBackgroundColor},
		canvas.NewLine(headerBorderColor),
	)

	h := &header{
		Widget: &backgroundColorWrapper{
			vbox, headerBackgroundColor},
		pages:         pages,
		box:           hbox,
		activeItems:   active,
		inactiveItems: inactive,
	}

	h.Refresh()

	return h
}

// Refresh overrides the corresponding method of fyne.CanvasObject.
func (h *header) Refresh() {
	for i := range h.activeItems {
		var item fyne.CanvasObject

		if i == h.activeIndex {
			item = h.activeItems[i]
		} else {
			item = h.inactiveItems[i]
		}

		if h.pages[i].hidden {
			item.Hide()
		} else {
			item.Show()
		}

		h.box.Children[i] = item
	}

	h.box.Refresh()
}

func (h *header) setPage(index int) bool {
	if index >= 0 && index < len(h.activeItems) {
		h.activeIndex = index
		h.Refresh()
		return true
	}
	return false
}

type backgroundColorWrapper struct {
	fyne.Widget
	backgroundColor color.Color
}

func (bcw *backgroundColorWrapper) CreateRenderer() fyne.WidgetRenderer {
	return &backgroundColorRenderer{
		bcw.Widget.CreateRenderer(), bcw.backgroundColor}
}
```

**Comment by andydotxyz** [comment]
I'm not sure how to use that code to replicate the issue?

Also the code does not show `header.CreateRenderer()` and I would guess the issue is likely with the renderer setup / refresh.

**Comment by ababo** [comment]
Oh I forgot to attach it.

```go
type backgroundColorRenderer struct {
	fyne.WidgetRenderer
	backgroundColor color.Color
}

func (bcg *backgroundColorRenderer) BackgroundColor() color.Color {
	return bcg.backgroundColor
}
```

**Comment by andydotxyz** [comment]
Can you also please include the content of `header.CreateRenderer()`?

It would be much more helpful if you could provide a complete, minimal code sample to replicate the issue.

**Comment by ababo** [comment]
There is no `header.CreateRenderer()`.

**Comment by andydotxyz** [comment]
I'm a little confused. If `header` is a `fyne.Widget` then how can it not have `CreateRenderer()`?

**Comment by ababo** [comment]
It contains anonymous `Widget` field, so it inherits its `CreateRenderer()`.

**Comment by andydotxyz** [comment]
Oh, I think I see - you're passing this to a Widget set later.
Hmm.
Wouldn't that mean that 'h.box.Refresh()' should be 'h.Widget.Refresh().
It's a little tricky to follow but it seems like you have half extended an anonymous widget, but half made your own.

Glitches in Rendering usually boil down to a Widget not refreshing the correct renderer - which could be the case with that line above.

**Comment by ababo** [comment]
@andydotxyz It looks like switching `image.Image` items in `canvas.Image.Image` instead of `canvas.Image` items in `widget.Box.Children` fixes the issue.

**Comment by andydotxyz** [comment]
I'm glad it's fixed but am still a little confused. Is this changing code that was inside the 'createImage(...)' function? I don't remember seeing the actual image load code above.

**Comment by ababo** [comment]
`CreateImage()` function is pretty straightforward:

```go
func createImage(path string) *canvas.Image {
	res := &fyne.StaticResource{path, util.ReadEmbeddedFile(path)}
	img := canvas.NewImageFromResource(res)
	return img
}
```

The working header version:

```go
type header struct {
	fyne.Widget
	pages    []*page
	box      *widget.Box
	active   []image.Image
	inactive []image.Image
	index    int
}

func newHeader(pages []*page) *header {
	var active []image.Image
	var inactive []image.Image
	var objects []fyne.CanvasObject

	for _, page := range pages {
		active = append(active,
			util.DecodeEmbeddedPNG(page.activeHeaderImage))
		inactive = append(inactive,
			util.DecodeEmbeddedPNG(page.inactiveHeaderImage))

		img := &canvas.Image{FillMode: canvas.ImageFillStretch}
		img.SetMinSize(fyne.Size{headerItemWidth, headerItemHeight})
		objects = append(objects, img)
	}

	hbox := widget.NewHBox(objects...)
	vbox := widget.NewVBox(
		&backgroundColorWrapper{hbox, headerBackgroundColor},
		canvas.NewLine(headerBorderColor),
	)

	h := &header{
		Widget: &backgroundColorWrapper{
			vbox, headerBackgroundColor},
		pages:    pages,
		box:      hbox,
		active:   active,
		inactive: inactive,
	}

	h.Refresh()

	return h
}

// Refresh overrides the corresponding method of fyne.CanvasObject.
func (h *header) Refresh() {
	for i := range h.active {
		img := h.box.Children[i].(*canvas.Image)

		if i == h.index {
			img.Image = h.active[i]
		} else {
			img.Image = h.inactive[i]
		}

		if h.pages[i].hidden {
			img.Hide()
		} else {
			img.Show()
		}

		img.Refresh()
	}
}

func (h *header) setPage(index int) bool {
	if index >= 0 && index < len(h.active) {
		h.index = index
		h.Refresh()
		return true
	}
	return false
}

```

**Comment by ababo** [comment]
Generic question regarding the second issue. Is there a way to show window content only when it finished laying out?

**Comment by andydotxyz** [comment]
Looking at the above code it could probably be simplified - you don't have to do the image decoding, just store the resource and do `img.Resource = h.active[i]` instead...

**Comment by andydotxyz** [comment]
> Generic question regarding the second issue. Is there a way to show window content only when it finished laying out?

It should not be possible for a window to appear without layed out content. The object tree is supposed to be arranged in preparation for render before the window appears.

Taking 3 seconds seems like a more major issue than not laying out in time - is it possible there is some external event occuring that adjusts what will be displayed?

**Comment by andydotxyz** [comment]
It seems from the comments abouve that this is resolved. Please re-open with more information if that is not the case.

**Comment by ababo** [comment]
Actually the issue is not resolved, but rather has become much more rare after moving to Fyne 1.4.0.
