### ISSUE TITLE
Update Android Status Bar Text / Icon color based on theme/night mode

### ISSUE THREAD

**Issue by stuartmscott** [fyne-io/fyne#1442]
Android Apps can draw below the status and navigation bars, however if the App background is white the elements inside the status and navigation become invisible as they are also white. Android will switch the elements to black if it is aware of the App's background colour, therefore Fyne needs to communicate the current theme's colour scheme to Android.

**Comment by s77rt** [comment]
Any update on this?

**Comment by andydotxyz** [comment]
We generally post updates when there are changes, we are still planning to work on this for the release tagged.

**Comment by andydotxyz** [comment]
the PR #2230 fixes the action bar, but for some reason the status bar still has a problem, it will not switch into dark text (light mode)... Looking for anyone who can help on this.

**Comment by andydotxyz** [comment]
Thanks @yebowhatsay - if it can be done in Java then we can call that from our code. Looks like the key in that article is:
```
if (Build.VERSION.SDK_INT >= 21) {
            Window window = this.getWindow();
            window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
            window.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
            window.setStatusBarColor(this.getResources().getColor(R.color.colorPrimaryDark));
 }
```

However we will need to convert our colours into Android ones. I had hoped we could just tell android "use light theme bar" like on iOS, but this may work instead.

Let's not hide the status bar, it is a useful feature of the platform.

**Comment by yebowhatsay** [comment]
Would have loved to help port this to Fyne, but really don't know where to get started.
Thanks, @andydotxyz !!!

**Comment by andydotxyz** [comment]
> Would have loved to help port this to Fyne, but really don't know where to get started.

You can see some of our other Android bridge code in the `android.c` files (there are 2) as we are in the middle of refactoring the mobile driver.

**Comment by yebowhatsay** [comment]
Thanks @andydotxyz . I am  having a go at cgo and studying the c/java code in the project.

**Comment by sanguohot** [comment]
> refactoring

The same problem. I have changed the background color to fix it. Thanks for reminding.
```
func (*CustomTheme) Color(n fyne.ThemeColorName, v fyne.ThemeVariant) color.Color {
	switch n {
	case theme.ColorNameBackground:
		return &color.NRGBA{R: 204, G: 232, B: 207, A: 255}
	default:
		return theme.DefaultTheme().Color(n, v)
	}
}
```

**Comment by andydotxyz** [comment]
Fixed on develop, will be in next release (at last!)

**Comment by hkparker** [comment]
I think I'm still experiencing this on 2.7.4, should I report it or is this actually in the 2.8 pipeline?

**Comment by hkparker** [comment]
Screenshots of dark mode and light mode for me, on the develop branch right now

<img width="1080" height="604" alt="Image" src="https://github.com/user-attachments/assets/f3f5cad8-f509-449e-b0b8-62864537752a" />
<img width="1078" height="585" alt="Image" src="https://github.com/user-attachments/assets/7a46c9e1-fded-490d-8755-dd779a4a187b" />

**Comment by andydotxyz** [comment]
Can you check that you're also using the latest Fyne CLI from tools?

**Comment by hkparker** [comment]
Ah of course, I need the new dex.  I just tried with 1.7.1 and main and sill don't see any icons up there in either case when the app is white (other than the battery).  I am using the "forced variant" theme pattern, perhaps that's relevant?  Are the icon colors being set by the system theme (which fyne is supposed to follow), and when I override that with the forced variant, it doesn't effect the system's themes and therefore doesn't effect the icon colors?

**Comment by hkparker** [comment]
I tried taking the code that sets the bar and put it my app as JNI.  It works when I set the theme now, if I go light mode and manually call that function to be light, the bar works.  For some reason calling it at startup doesn't work yet, but I'm pretty sure I'm experiencing this because I'm overriding the variant.

**Comment by andydotxyz** [comment]
I'm not quite following, but it sounds like your app is ignoring the system theme. Android does not know that your app is doing that, so it could collide. If you have an app that draws backgrounds with a theme that is incompatible with the system then we need either: 

* the app to draw a compatible background outside the interactive area with your background drawn only as content, or
* a feature request to force apps to display in a certain variant at the system level

Personally I try to have my custom themes respect light/dark so it matches system even with custom colours etc.

**Comment by hkparker** [comment]
Yeah, I'm ignoring the system theme.  It would be nice to have the system theme be in option, but letting users override the system theme is an important feature to me, so for now I just have "light mode" and "dark mode" (no "system theme" mode yet).

What I changed to get the android bar working was just manually calling `updateSystemBarsAppearance` from #6134 via the JNI to match the theme that the user chooses.
