### ISSUE TITLE
Infinite progress bar starts again when containing window is closed

### ISSUE THREAD

**Issue by steveoc64** [fyne-io/fyne#202]
In fyne_demo, open the Widgets demo, go to progress bar.

observe that the progress widget gets calls to Refresh() which calls updateBar()

Now close the window.

observe that Destroy() gets called, as expected.

However, start() also gets called just after that (at which point Im printing a stack trace to show why its getting called again.

Its in driver/gl/loop.go .. during walkObjects() .. which must end up calling draw() on the progress bar, which in turn creates a new renderer, and starts running it again.

At this point, the progress bar window is no longer displayed ... but updateBar keeps getting called.

Not suggesting any solutions at this stage .....
 
```
1.170782ms [   5] (      64):   4123912:  72810744:    950272 <-   [updateBar]
1.86828ms [   5] (     192):   4124104:  72810744:    950272 <-   [refresh]
2.468196ms [   5] (       0):   4124104:  72810744:    950272 <-   [updateBar]
2.124908ms [   5] (   10024):   4134128:  72810744:    950272 <-   [destroy]
1.983095ms [   4] (     240):   4133888:  72810744:    950272 <-   [start()]
goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0xc0000141a8, 0x61d9c0, 0x6d5990)
	/usr/local/go1.12/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go1.12/src/runtime/debug/stack.go:16 +0x22
fyne.io/fyne/widget.(*infProgressRenderer).start(0xc0006420f0)
	/home/steve/go/src/fyne.io/fyne/widget/progressbarinfinite.go:105 +0xb8
fyne.io/fyne/widget.(*ProgressBarInfinite).CreateRenderer(0xc0006a6030, 0x67dc80, 0xc0006a6030)
	/home/steve/go/src/fyne.io/fyne/widget/progressbarinfinite.go:210 +0x12d
fyne.io/fyne/widget.Renderer(0x6df5c0, 0xc0006a6030, 0x4, 0x88)
	/home/steve/go/src/fyne.io/fyne/widget/widget.go:79 +0xaf
fyne.io/fyne/driver/gl.(*glCanvas).walkObjects(0xc000636000, 0x6def00, 0xc0006a6030, 0x4, 0x25, 0x6a9040)
	/home/steve/go/src/fyne.io/fyne/driver/gl/draw.go:45 +0x156
fyne.io/fyne/driver/gl.(*glCanvas).walkObjects(0xc000636000, 0x6deb40, 0xc00060c120, 0x4, 0x4, 0x6a9040)
	/home/steve/go/src/fyne.io/fyne/driver/gl/draw.go:46 +0x1eb
fyne.io/fyne/driver/gl.(*glCanvas).walkObjects(0xc000636000, 0x6df020, 0xc0006420a0, 0x0, 0x0, 0x6a9040)
	/home/steve/go/src/fyne.io/fyne/driver/gl/draw.go:46 +0x1eb
fyne.io/fyne/driver/gl.(*window).closed(0xc0000e2080, 0xc0000e2000)
	/home/steve/go/src/fyne.io/fyne/driver/gl/window.go:349 +0x69
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw.goWindowCloseCB(0x271cc10)
	/home/steve/go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/window.go:197 +0x49
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw._cgoexpwrap_09a112f9b34b_goWindowCloseCB(0x271cc10)
	_cgo_gotypes.go:2239 +0x2b
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw._Cfunc_glfwPollEvents()
	_cgo_gotypes.go:1197 +0x41
fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw.PollEvents()
	/home/steve/go/src/fyne.io/fyne/vendor/github.com/go-gl/glfw/v3.2/glfw/window.go:777 +0x22
fyne.io/fyne/driver/gl.(*gLDriver).runGL(0xc00000e780)
	/home/steve/go/src/fyne.io/fyne/driver/gl/loop.go:77 +0x1d5
fyne.io/fyne/driver/gl.(*gLDriver).Run(0xc00000e780)
	/home/steve/go/src/fyne.io/fyne/driver/gl/driver.go:58 +0x43
fyne.io/fyne/driver/gl.(*window).ShowAndRun(0xc0000e2180)
	/home/steve/go/src/fyne.io/fyne/driver/gl/window.go:303 +0x58
main.main()
	/home/steve/go/src/fyne.io/fyne/cmd/fyne_demo/main.go:104 +0xe45
  1.413792ms [   5] (     432):   4134320:  72810744:    983040 <-   [loop is starting]
  1.655688ms [   5] (     416):   4134736:  72810744:    983040 <-   [refresh]
  1.359942ms [   5] (       0):   4134736:  72810744:    950272 <-   [updateBar]
  1.673122ms [   5] (     256):   4134992:  72810744:    950272 <-   [refresh]
  1.611382ms [   5] (       0):   4134992:  72810744:    950272 <-   [updateBar]
  1.896616ms [   5] (       0):   4134992:  72810744:    950272 <-   [refresh]
  1.604742ms [   5] (    1024):   4133968:  72810744:    950272 <-   [updateBar]
```

**Comment by steveoc64** [comment]
I see whats happening - in driver/gl/draw.go it calls Renderer() again to range over the objects.

```
	case fyne.Widget:
		offset := co.Position().Add(pos)
		f(obj, offset)

		for _, child := range widget.Renderer(co).Objects() {
			c.walkObjects(child, offset, f)
		}
```

So this will create a new renderer, which is a bit nasty.  Nasty because some widgets (like infiniteProgressBar) might do all sorts of interesting things ... such as starting a new animation goroutine, etc.

Having a think about it.

**Comment by steveoc64** [comment]
Played around inside walkObject, and added a function GetRenderer(co) which returns (fyne.WidgetRenderer, bool) and doesnt create one.

Put that in place of the widget.Renderer(co) above ... but thats no good either.

Only simple way to fix this is to get the infinite progress bar to start life in an un-animated state.

If its on the 2nd tab, then it gets a Show() message which starts the animation.

If it starts life on the 1st tab, then add Start() on creation

```
func makeProgressTab() fyne.Widget {
	progress := widget.NewProgressBar()
	infProgress := widget.NewProgressBarInfinite()
	infProgress.Start()
```

still thinking about it ....

**Comment by steveoc64** [comment]
Appears to be bulletproof now after PR https://github.com/fyne-io/fyne/pull/203

**Comment by andydotxyz** [comment]
It looks like the real bug is that walkObjects() is not ignoring hidden objects...
I can't tell the impact as I'm not on the code right now but that seems like a more logical change within the current code design.

**Comment by andydotxyz** [comment]
This should be resolved following some work in this area - can you confirm @steveoc64?

**Comment by steveoc64** [comment]
sounds about right.  Will have to get myself back up to speed with the latest, and see if its still an issue even.

Good excuse to add the infinitePB to my current project and give it a good workout

**Comment by andydotxyz** [comment]
Could you please check about latest develop branch? :)

**Comment by andydotxyz** [comment]
I can no longer replicate this
