### ISSUE TITLE
Sometimes the app crashes when a password entry gets focus

### ISSUE THREAD

**Issue by ababo** [fyne-io/fyne#2104]
We have a PIN-entry page that intermittently (actually pretty rarely) crashes when the corresponding password entry gets focused. Here's a log:
```
2021/03/17 16:41:49 Fyne error:  GLFW poll event error: runtime error: invalid memory address or nil pointer dereference
2021/03/17 16:41:49   At: C:/msys64/home/ababo/go/pkg/mod/fyne.io/fyne/v2@v2.0.1/internal/driver/glfw/loop.go:220
```
Platform: Windows 10
Go version: go1.15.7 darwin/amd64
Fyne version: v2.0.1

**Comment by andydotxyz** [comment]
Please test against `develop` as this may have been fixed in preparation for `v2.0.2`

**Comment by ababo** [comment]
I still get these annoying error messages both on Mac and Windows, but they don't seem to impact the workflow.

**Comment by andydotxyz** [comment]
Can you confirm what the annoying messages are? They could have changed with the release of v2.0.2?

It could also help to share the code where you are requesting focus as it may be related.

**Comment by ababo** [comment]
It looks like they are not related to the crash.
```
021/04/02 16:08:25 Fyne error:  GLFW poll event error: runtime error: invalid memory address or nil pointer dereference
2021/04/02 16:08:25   At: /Users/ababo/go/pkg/mod/fyne.io/fyne/v2@v2.0.2/internal/driver/glfw/loop.go:220
2021/04/02 16:08:25 Fyne error:  GLFW poll event error: runtime error: invalid memory address or nil pointer dereference
2021/04/02 16:08:25   At: /Users/ababo/go/pkg/mod/fyne.io/fyne/v2@v2.0.2/internal/driver/glfw/loop.go:220
2021/04/02 16:08:48 Fyne error:  GLFW poll event error: runtime error: invalid memory address or nil pointer dereference
2021/04/02 16:08:48   At: /Users/ababo/go/pkg/mod/fyne.io/fyne/v2@v2.0.2/internal/driver/glfw/loop.go:220
2021/04/02 16:08:55 Fyne error:  GLFW poll event error: runtime error: invalid memory address or nil pointer dereference
2021/04/02 16:08:55   At: /Users/ababo/go/pkg/mod/fyne.io/fyne/v2@v2.0.2/internal/driver/glfw/loop.go:220
2021/04/02 16:08:55 Fyne error:  GLFW poll event error: runtime error: invalid memory address or nil pointer dereference
2021/04/02 16:08:55   At: /Users/ababo/go/pkg/mod/fyne.io/fyne/v2@v2.0.2/internal/driver/glfw/loop.go:220
2021/04/02 16:08:55 Fyne error:  GLFW poll event error: runtime error: invalid memory address or nil pointer dereference
2021/04/02 16:08:55   At: /Users/ababo/go/pkg/mod/fyne.io/fyne/v2@v2.0.2/internal/driver/glfw/loop.go:220
2021/04/02 16:08:56 Fyne error:  GLFW poll event error: runtime error: invalid memory address or nil pointer dereference
2021/04/02 16:08:56   At: /Users/ababo/go/pkg/mod/fyne.io/fyne/v2@v2.0.2/internal/driver/glfw/loop.go:220
```

**Comment by andydotxyz** [comment]
No other errors reported earlier in the application?
That is a generic catch-all that tries to avoid the app crashing whilst in the GLFW library code...

**Comment by ababo** [comment]
No other errors, just those repeatedly... But the app works as expected.

**Comment by andydotxyz** [comment]
Can you help with the other part as well please?

> It could also help to share the code where you are requesting focus as it may be related.

**Comment by ababo** [comment]
But sometimes it appears before the focusing code.

**Comment by andydotxyz** [comment]
Can you please check against `develop` again @ababo ? Since the focus code was updated for v2.1 this may be resolved.

**Comment by ababo** [comment]
I think I didn't reproduced the issue for some time. I guess we can close it now. I will reopen if I see it again.
