### ISSUE TITLE
mac os compile windows executable disappears before compile completed

### ISSUE THREAD

**Issue by lengnuan-v** [fyne-io/fyne#2324]
`
CGO_ENABLED="1" GOOS="windows" GOARCH="amd64" CC="x86_64-w64-mingw32-gcc" fyne package -os windows -icon app.png 
`
mac os compile windows Nothing at all

No compiled file

**Comment by andydotxyz** [comment]
Please provide any errors and the file listing of the directory after it completes.

**Comment by lengnuan-v** [comment]
https://user-images.githubusercontent.com/45681358/125879485-f977dcc3-e948-4009-9cd1-3ac2adcb7d81.mp4

**Comment by andydotxyz** [comment]
In your video I see `fyne.exe`, that is the windows executable.
I don't understand what is missing?

**Comment by lengnuan-v** [comment]
And finally disappeared. @andydotxyz

**Comment by andydotxyz** [comment]
Aha, this issue was fixed in April (e040bd85) - if you install the latest release of `fyne.io/fyne/v2/cmd/fyne` then the problem will go away

**Comment by andydotxyz** [comment]
Closing as duplicate because it was already solved.

**Comment by lengnuan-v** [comment]
This is the latest version, but it still appears, and the generated EXE simply disappears

**Comment by lengnuan-v** [comment]
![Uploading QQ20210719-110311@2x.png…]()

**Comment by lengnuan-v** [comment]
<img width="765" alt="QQ20210719-110311@2x" src="https://user-images.githubusercontent.com/45681358/126096740-8d8f2189-ef31-4116-8b73-e3b596ac6ddc.png">

**Comment by lengnuan-v** [comment]
<img width="482" alt="12" src="https://user-images.githubusercontent.com/45681358/126096785-360d9ee2-02aa-4067-a664-bdb42c7dc1f4.png">

**Comment by lengnuan-v** [comment]
@andydotxyz

**Comment by lengnuan-v** [comment]
Or does Mac OS only generate Mac OS, Windows generates Windows, not cross-platform?

**Comment by andydotxyz** [comment]
> Or does Mac OS only generate Mac OS, Windows generates Windows, not cross-platform?

the Fyne tool is fully capable of cross-compiling. The version in your module is not necessarily the same as the command line version. What is the result of running `fyne version`

**Comment by lengnuan-v** [comment]
<img width="300" alt="11" src="https://user-images.githubusercontent.com/45681358/126114415-3c2d56fa-f7db-45fa-ba43-da5409f8142f.png">
@andydotxyz

**Comment by andydotxyz** [comment]
Ah, my apologies, the fix is not yet released - it is on branch `release/v2.0.x` and will be released with v2.0.4 in the next week or two.
You can build the `fyne` tool from that branch if you would like the fix now.
