### ISSUE TITLE
sequential writes to preferences does not save to file

### ISSUE THREAD

**Issue by zivoy** [fyne-io/fyne#2449]
### Describe the bug:

Setting a string value with the Preferences API more than once in a row causes it to not write the latter ones to the file. unless a gap is introduced.

### To Reproduce:
Steps to reproduce the behaviour:
here is a sample program
```go
a := app.NewWithID("TESTING")
fmt.Println("Before setting")
fmt.Println(a.Preferences().String("a"))
fmt.Println(a.Preferences().String("b"))
a.Preferences().SetString("a", "aaaaaaaaaaaaa")
//<-time.After(100*time.Millisecond)
a.Preferences().SetString("b", "bbbbbbbbbbbbb")
fmt.Println("After")
fmt.Println(a.Preferences().String("a"))
fmt.Println(a.Preferences().String("b"))
```
take this program and run it twice.
you will see that on the second run only `a` is set while `b` is still nothing. 
now uncomment the line in the middle and run it twice more.
now both `a` and `b` are set.

### Device (please complete the following information):
 - **OS:** Windows
 - **Version:** 10
 - **Go version:** 1.16.7
 - **Fyne version:** 2.0.4

**Comment by andydotxyz** [comment]
Thanks for the report, this should be fixed in PR #2450, please do test and confirm :) @zivoy

**Comment by zivoy** [comment]
It's fixed, works without the need for adding the delay now.

**Comment by dolanor** [comment]
I feel it still exists somehow.

With this test, it fails if I don't put a sleep

```go
func TestFynePreferences_SetString(t *testing.T) {
	a := app.NewWithID("test-fyne-preferences")
	defer a.Quit()

	prefs := a.Preferences()

	prefs.SetString("test", "1")
	prefs.SetString("test", "2")
	prefs.SetString("test", "3")
	prefs.SetString("test", "4")
	//time.Sleep(time.Second)
	t.Log("done")
}
```

Checking in the preferences.json file afterwards shows it was not totally updated (it shows 1 or 2, but never 4 on my machine)

**Comment by dolanor** [comment]
After discussing with @andydotxyz . It seems it's a bug in the test runner (the fyne.App instance that is used in the tests) and this should be improved.

Running the test while getting the value from the preferences will make this work.

```go
func TestFynePreferences_SetString(t *testing.T) {
	a := app.NewWithID("test-fyne-preferences")
	defer a.Quit()

	prefs := a.Preferences()

	prefs.SetString("test", "1")
	prefs.SetString("test", "2")
	prefs.SetString("test", "3")
	prefs.SetString("test", "4")
	//time.Sleep(time.Second)
	t.Log("done")
	got := prefs.String("test")
	want := "4"
	if got != want {
		t.Fatalf("got != want. got = %s, want = %s", got, want)
	}
}
```

**Comment by andydotxyz** [comment]
> After discussing with [@andydotxyz](https://github.com/andydotxyz) . It seems it's a bug in the test runner (the fyne.App instance that is used in the tests) and this should be improved.

Yes indeed. Please open a new issue for that problem as it is a different problem to this closed issue (it was resolved for app runtime 4 years ago)
