### ISSUE TITLE
Links in Markdown/Rich Text lists breaks formatting

### ISSUE THREAD

**Issue by alexrudd** [fyne-io/fyne#2911]
### Describe the bug:

Including a link at the end of an element in a list breaks the formatting when rendered:

```md
* [List item one](https://item1.com)
* [List item two](https://item2.com)
```

### To Reproduce:
Steps to reproduce the behaviour:

1. Create an application that uses the `NewRichTextFromMarkdown` widget
2. Pass in the markdown from above
3. Run the app and see the bug

### Screenshots:

![image](https://user-images.githubusercontent.com/3588652/162796702-c072cab6-84f0-42c9-a7ca-51628ea1d587.png)

### Example code:

```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello World")

	w.SetContent(widget.NewRichTextFromMarkdown(`
# Reproduce list bug

* [List item one](https://item1.com)
* [List item two](https://item2.com)

## Workaround using fullstops

* [List item one](https://item1.com).
* [List item two](https://item2.com).

## Without links

* Item one
* Item two
`))
	w.ShowAndRun()
}

```

### Device (please complete the following information):
 - **OS:** Windows
 - **Version:** 10.0.19043
 - **Go version:** 1.18.0
 - **Fyne version:** v2.1.4

**Comment by matwachich** [comment]
This is also the same thing for normal URL widget when placed in a VBox for example (the underline continues until the end)

**Comment by andydotxyz** [comment]
But that isn't a break in the formatting or layout - the line literally has that much space left so the Hyperlink is asked to fill the gap - like a text like would if there was no link.

**Comment by andydotxyz** [comment]
Fixed on develop and picking to 2.3.x release branch

**Comment by hdm** [comment]
Quick note that this still occurs on mouseover, just not in normal state:

<img width="268" alt="image" src="https://github.com/fyne-io/fyne/assets/1171392/c8e5e1ed-14f6-404b-a2a5-86852b9a63c4">

**Comment by andydotxyz** [comment]
That is not the same issue. You can see above that the bullets were in the wrong place.
There is a separate PR that reduces the length of the underline, but that is not merged yet.
