### ISSUE TITLE
panic: interface conversion: fyne.Layout is nil, not *widget.ListLayout

### ISSUE THREAD

**Issue by williambrode** [fyne-io/fyne#3369]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

This panic happens intermittently when my app is starting.  Unfortunately I only have a picture of the stacktrace right now:

<img width="567" alt="image" src="https://user-images.githubusercontent.com/5753045/199410668-651df545-943b-4b75-8488-2b7855694573.png">

The panic is here:

```go
func (l *List) Resize(s fyne.Size) {
	l.BaseWidget.Resize(s)
	l.offsetUpdated(l.scroller.Offset)
	l.scroller.Content.(*fyne.Container).Layout.(*listLayout).updateList(true)   <<<<<<<
}
```

The layout is supposed to be set by CreateRenderer:
```go
func (l *List) CreateRenderer() fyne.WidgetRenderer {
	...
	layout := &fyne.Container{}
	l.scroller = widget.NewVScroll(layout)
	layout.Layout = newListLayout(l)
	...
}
```

So it appears that Resize can be called before CreateRenderer - in which case I think we should probably just check that the Layout is not null in Resize() before trying to update it?

```go
func (l *List) Resize(s fyne.Size) {
	l.BaseWidget.Resize(s)
	l.offsetUpdated(l.scroller.Offset)
        if l.scroller.Content.(*fyne.Container).Layout != nil {
                    l.scroller.Content.(*fyne.Container).Layout.(*listLayout).updateList(true)
        }
}
```

### How to reproduce

Included code sample causes the panic

### Example code

```go
myList := widget.NewList(func() int {return 0}, func() fyne.CanvasObject {return widget.NewButton("", func() {})}, func(lii widget.ListItemID, co fyne.CanvasObject) {})
	myList.Resize(myList.Size())
```

### Fyne version

2.2.3

### Go compiler version

1.19.1

### Operating system

Windows

### Operating system version

Windows 10

**Comment by andydotxyz** [comment]
I think the crash varies based on the Fyne version. Can you see if this alternative fix helps?

```go
index 51671ce6..6c4c71f7 100644
--- a/widget/list.go
+++ b/widget/list.go
@@ -111,6 +111,10 @@ func (l *List) scrollTo(id ListItemID) {
 // Resize is called when this list should change size. We refresh to ensure invisible items are drawn.
 func (l *List) Resize(s fyne.Size) {
        l.BaseWidget.Resize(s)
+       if l.scroller == nil {
+               return
+       }
+
        l.offsetUpdated(l.scroller.Offset)
        l.scroller.Content.(*fyne.Container).Layout.(*listLayout).updateList(true)
 }
```

**Comment by williambrode** [comment]
Ah sorry, I cut out our error handling code in the stack trace but should have showed you the panic message:
<img width="536" alt="image" src="https://user-images.githubusercontent.com/5753045/199835343-89b64624-cdc5-4225-928e-767927e83975.png">

Its the Layout that is nil.

**Comment by Jacalz** [comment]
This was fixed a while back. Closing

**Comment by williambrode** [comment]
I can confirm this is still an issue on fyne 2.3.5 - is there reason to believe it was fixed after that point?

Panic backtrace:
> fyne.io/fyne/v2@v2.3.5/widget/list.go in (*List).Resize at line 156
> fyne.io/fyne/v2@v2.3.5/layout/maxlayout.go in (*maxLayout).Layout at line 22
> fyne.io/fyne/v2@v2.3.5/container.go in (*Container).layout at line 195
> fyne.io/fyne/v2@v2.3.5/container.go in NewContainerWithLayout at line 51
> fyne.io/fyne/v2@v2.3.5/container/container.go in New at line 12
> fyne.io/fyne/v2@v2.3.5/container/layouts.go in NewMax at line 91

In CreateRenderer we have:
```go
l.scroller = widget.NewVScroll(layout)
layout.Layout = newListLayout(l)
```
So there is a time when scroller is not nil, but Layout is not set.

But in Resize we only check if `scroller != nil `before assuming Layout is populated:
 ```go
        if l.scroller == nil {
		return
	}

	l.offsetUpdated(l.scroller.Offset)
	l.scroller.Content.(*fyne.Container).Layout.(*listLayout).updateList(true)
```

**Comment by andydotxyz** [comment]
Please update to `v2.4.0` and check the fix, the way list init was handled changed from 2.3 to 2.4

**Comment by williambrode** [comment]
I was not being sarcastic - I was asking if you thought it might be fixed in 2.4+, which you've confirmed it might be.

**Comment by Jacalz** [comment]
The issue was closed because https://github.com/fyne-io/fyne/pull/3453 was merged saying that it fixed the issue. If anything, the issue should be fixed with v2.4.0

**Comment by Jacalz** [comment]
v2.3.5 is no longer the latest version...
