### ISSUE TITLE
Entry does not show the last (few) changes when updating a binding.String in a fast succession 

### ISSUE THREAD

**Issue by Roemer** [fyne-io/fyne#4082]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

As discussed in Slack (https://gophers.slack.com/archives/CB4QUBXGQ/p1689959990702439) there seems to be an issue when a `binding.String` is bound to an `Entry` and is quickly updated multiple times. In that case, the `Entry` does not get all the last changes until the binding is updated again.

### How to reproduce

1. Run the example code from below
2. Have a look at the Window (and optionally the terminal output). Theoretically it should display `a` and `b` randomly counting from 0 to 19. But you will just see a nothing or a few entries. Then after 5 seconds, it will add a `final` string and suddenly renders all missing parts.

### Screenshots

![image](https://github.com/fyne-io/fyne/assets/393641/9bb882c8-44c7-47a1-8e4e-c0b17838552f)

### Example code

```go
package main

import (
	"fmt"
	"strconv"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Test")
	w.Resize(fyne.NewSize(700, 300))

	textBinding := binding.NewString()
	widget := widget.NewEntryWithData(textBinding)

	logChannel := make(chan string, 100)
	go func() {
		for text := range logChannel {
			fmt.Println(text)
			existingText, _ := textBinding.Get()
			fmt.Println(existingText)
			newText := existingText + "," + text
			textBinding.Set(newText)
		}
	}()

	go func() {
		time.Sleep(time.Second * 1)
		for i := 0; i < 20; i++ {
			text := "a" + strconv.Itoa(i)
			logChannel <- text
			time.Sleep(time.Millisecond * 1)
		}
	}()
	go func() {
		time.Sleep(time.Second * 1)
		for i := 0; i < 20; i++ {
			text := "b" + strconv.Itoa(i)
			logChannel <- text
			time.Sleep(time.Millisecond * 1)
		}
	}()

	go func() {
		time.Sleep(time.Second * 5)
		logChannel <- "final"
	}()

	w.SetContent(widget)
	w.CenterOnScreen()
	w.ShowAndRun()
}
```

### Fyne version

v2.3.6-0.20230720061213-19e0c73660eb

### Go compiler version

1.20.6

### Operating system and version

Linux WSL2, Windows 10

**Comment by Roemer** [comment]
Probably related:
When then `Entry` contains a placeholder, a `Set` on the binding also seems not to work (at all or at least reliable).
See this example:
```go
package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Test")
	w.Resize(fyne.NewSize(700, 300))

	// Username
	sshUsernameBinding := binding.NewString()
	sshUsernameControl := widget.NewEntryWithData(sshUsernameBinding)
	sshUsernameControl.SetPlaceHolder("Username")
	sshUsernameBinding.Set("Test")

	w.SetContent(container.New(layout.NewFormLayout(), widget.NewLabel("Username"), sshUsernameControl))
	w.CenterOnScreen()
	w.ShowAndRun()
}
```

**Comment by Jacalz** [comment]
I think this might have been fixed on the `develop` branch. Would someone like to test?

**Comment by dan-frohlich** [comment]
Is this related to #4061 ?

**Comment by williambrode** [comment]
This is still happening on 2.4.3.  Here is my test case where you can't get the widget to show the value "2" using the button.  I think its a pretty big regression of the Entry widget with a binding - since the value shown to the user is wrong in many cases.  I may have to revert back to before the bug on my project or use a different widget.

```go
package main

import (
	"time"

	fyne "fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/data/binding"
	"fyne.io/fyne/v2/widget"
)

func main() {
	fyneApp := app.NewWithID("TestApp")

	win := fyneApp.NewWindow("TestWindow")
	win.Resize(fyne.NewSize(500, 500))
	boundString := binding.NewString()
	win.SetContent(
		container.NewVBox(
			widget.NewEntryWithData(boundString),
			widget.NewButton("change", func() {
				_ = boundString.Set("1")
				time.Sleep(10 * time.Millisecond)
				_ = boundString.Set("2")
			}),
		),
	)
	win.Show()

	fyneApp.Run()
}
```

**Comment by andydotxyz** [comment]
fixed on develop, will pick into 2.4.4
