### ISSUE TITLE
Window doesn't render when called for the first time from system tray and the last window was closed

### ISSUE THREAD

**Issue by mbaklor** [fyne-io/fyne#4163]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I have an app set up with a system tray and splash screen, where the main window is hidden on startup until you open it from the systray. What I found is that if I don't render the window before the splash screen closes the window won't render. On windows by resizing it renders, on ubuntu it doesn't even do that.

I did find that using `Hide` on the splash screen instead of `Close` avoids the issue, so it's something about the last visibly window calling `Close` I guess? Couldn't find anything I could understand in the sources.

### How to reproduce

build an app with a splash screen, no other window showing on startup, and a systray to open a window.

### Screenshots

I'm not on my windows machine now so I'll grab that later but here's the linux:
![image](https://github.com/fyne-io/fyne/assets/78748463/bb2a7551-af76-40b6-90de-15fee26d4f03)

### Example code

```go
func main() {
	a := app.New()
	label := widget.NewLabel("Window with content!")
	win := a.NewWindow("Render Test")
	win.SetContent(label)
	showWin := fyne.NewMenuItem("Show win", func() {
		win.Show()
	})
	menu := fyne.NewMenu("tray", showWin)

	if desk, ok := a.(desktop.App); ok {
		desk.SetSystemTrayMenu(menu)
	}
	if drv, ok := a.Driver().(desktop.Driver); ok {
		splash := drv.CreateSplashWindow()
		splash.SetContent(widget.NewLabel("Splash with content!"))
		splash.Show()
		go func() {
			time.Sleep(time.Second * 3)
			splash.Close()
		}()
	}
	win.SetCloseIntercept(func() {
		win.Hide()
	})
	a.Run()
}
```

### Fyne version

both latest (2.3.5) and develop (v2.3.6-0.20230815202934-6f2c727d711a)

### Go compiler version

1.20.5

### Operating system and version

windows 11, 10, kubuntu 5.27.4

**Comment by andydotxyz** [comment]
Fixed on develop

**Comment by mbaklor** [comment]
looks like this is still happening on develop (v2.3.6-0.20230824093032-28ab69056a4c), I think the problem isn't a window being reused but a window being rendered for the first time after the last existing window (besides the systray monitor) is closed
