### ISSUE TITLE
macOS Sonoma breaks “go run”

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fyne#4296]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Running a fyne app directly from the go compiler won’t launch (you get `Killed` error from the OS.
Packaged apps, even without signing, work fine.

### How to reproduce

1. Open any Fyne app
2. Run a terminal on macOS Sonoma
3. Type “go run .”

In the Console app you can see approx:

```
default	20:52:36.097192+0100	kernel	AMFI: '/private/var/folders/pc/1mt578kn6615qkxsygpwrw7m0000gn/T/go-build3020901906/b001/exe/fysion.app' has no CMS blob?
default	20:52:36.097199+0100	kernel	AMFI: '/private/var/folders/pc/1mt578kn6615qkxsygpwrw7m0000gn/T/go-build3020901906/b001/exe/fysion.app': Unrecoverable CT signature issue, bailing out.
default	20:52:36.110133+0100	kernel	ASP: Security policy would not allow process: 3636, /private/var/folders/pc/1mt578kn6615qkxsygpwrw7m0000gn/T/go-build3020901906/b001/exe/fysion.app
```

### Example code

Fyne example app

### Fyne version

2.4.0

### Go compiler version

1.20.4

### Operating system and version

macOS Sonoma

### Additional Information

It is killed by the gatekeeper due, but the result of “fyne package” works great, even when executing the embedded binary directly.

**Comment by andydotxyz** [comment]
See related fyne-io/terminal#40

**Comment by bamcop** [comment]
### I can build and run on macOS Sonoma, Apple M1 Silicon, using go1.20.7
```sh
(base) ➜  fyneterm git:(master) sw_vers                   
ProductName:		macOS
ProductVersion:		14.0
BuildVersion:		23A344
(base) ➜  fyneterm git:(master) git remote -v
origin	https://github.com/fyne-io/terminal.git (fetch)
origin	https://github.com/fyne-io/terminal.git (push)
(base) ➜  fyneterm git:(master) git rev-parse --short HEAD
021d89e
(base) ➜  fyneterm git:(master) go version
go version go1.20.7 darwin/arm64
(base) ➜  fyneterm git:(master) go build .
# github.com/fyne-io/terminal/cmd/fyneterm
ld: warning: ignoring duplicate libraries: '-lobjc'
ld: warning: '/private/var/folders/ll/mwh6q2_11bx1x28xgdvgsz040000gn/T/go-link-1669995110/go.o' has malformed LC_DYSYMTAB, expected 121 undefined symbols to start at index 21412, found 305 undefined symbols starting at index 125
(base) ➜  fyneterm git:(master) ./fyneterm 
2023-10-12 09:25:54.782 fyneterm[22233:3849696] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
(base) ➜  fyneterm git:(master)
```

### but signal killed when using go1.21.2
```sh
(base) ➜  fyneterm git:(master) go version
go version go1.21.2 darwin/arm64
(base) ➜  fyneterm git:(master) go build .
# github.com/fyne-io/terminal/cmd/fyneterm
ld: warning: ignoring duplicate libraries: '-lobjc'
(base) ➜  fyneterm git:(master) ./fyneterm 
[1]    38208 killed     ./fyneterm
(base) ➜  fyneterm git:(master)
```

hope the information above has been of some help/

**Comment by andydotxyz** [comment]
The info about "killed" is in Console app, not the command line - see if you can find the log items showing why your app was killed.

**Comment by bamcop** [comment]
Console app info

```sh
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               fyneterm [58134]
Path:                  /Users/USER/*/fyneterm
Identifier:            fyneterm
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        zsh [67345]
Responsible:           Terminal [4556]
User ID:               501

Date/Time:             2023-10-12 18:13:35.4870 +0800
OS Version:            macOS 14.0 (23A344)
Report Version:        12
Anonymous UUID:        62E55472-60A8-EA44-03CF-FFCF0C21662C

Sleep/Wake UUID:       F95ABA04-D76F-43C4-930F-1815EE54531E

Time Awake Since Boot: 280000 seconds
Time Since Wake:       32967 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))
Exception Codes:       UNKNOWN_0x32 at 0x0000000102edb2e0
Exception Codes:       0x0000000000000032, 0x0000000102edb2e0

Termination Reason:    Namespace CODESIGNING, Code 2 Invalid Page

VM Region Info: 0x102edb2e0 is in 0x102ed4000-0x1035c8000;  bytes after start: 29408  bytes before end: 7261471
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  __TEXT                      102ed4000-1035c8000    [ 7120K] r-x/r-x SM=COW  ...ER/*/fyneterm
      __DATA_CONST                1035c8000-103708000    [ 1280K] r--/rw- SM=COW  ...ER/*/fyneterm

Kernel Triage:
VM - (arg = 0x0) A memory corruption was found in executable text


Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   fyneterm                      	       0x102edb2e0 */abi.Name.Name + 0
1   fyneterm                      	       0x102ee62a4 runtime.(*itab).init + 388

Thread 1:
0   libsystem_kernel.dylib        	       0x184c2dea8 __semwait_signal + 8
1   libsystem_c.dylib             	       0x184b114c4 nanosleep + 220
2   libsystem_c.dylib             	       0x184b113dc usleep + 68
3   fyneterm                      	       0x102f465c4 runtime.usleep_trampoline.abi0 + 20
4   fyneterm                      	       0x102f45328 runtime.asmcgocall.abi0 + 200

Thread 2:
0   libsystem_kernel.dylib        	       0x184c2e0ac __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x184c6b5fc _pthread_cond_wait + 1228
2   fyneterm                      	       0x102f46948 runtime.pthread_cond_wait_trampoline.abi0 + 24
3   fyneterm                      	       0x102f45328 runtime.asmcgocall.abi0 + 200

Thread 3:
0   libsystem_kernel.dylib        	       0x184c2e0ac __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x184c6b5fc _pthread_cond_wait + 1228
2   fyneterm                      	       0x102f46948 runtime.pthread_cond_wait_trampoline.abi0 + 24
3   fyneterm                      	       0x102f45328 runtime.asmcgocall.abi0 + 200

Thread 4:
0   libsystem_kernel.dylib        	       0x184c2e0ac __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x184c6b5fc _pthread_cond_wait + 1228
2   fyneterm                      	       0x102f46948 runtime.pthread_cond_wait_trampoline.abi0 + 24
3   fyneterm                      	       0x102f45328 runtime.asmcgocall.abi0 + 200

Thread 5:
0   libsystem_kernel.dylib        	       0x184c2e0ac __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x184c6b5fc _pthread_cond_wait + 1228
2   fyneterm                      	       0x102f46948 runtime.pthread_cond_wait_trampoline.abi0 + 24
3   fyneterm                      	       0x102f45328 runtime.asmcgocall.abi0 + 200


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x00000001035ccd0c   x1: 0x0000000000003b0c   x2: 0x0000000000003b0c   x3: 0x00000001035c9200
    x4: 0x0000000103700fb0   x5: 0x000000010368ef90   x6: 0x0000000103648ee0   x7: 0x000000010368efd0
    x8: 0x0000000000000001   x9: 0x0000000000000000  x10: 0x0000000000000000  x11: 0x0000000000000001
   x12: 0x0000000000000033  x13: 0x000000016cf2a790  x14: 0x0000000000000005  x15: 0x0000000000000001
   x16: 0x00000140003003a0  x17: 0x000001400031fb10  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000001400031fde8  x21: 0x00000140003bdf10  x22: 0x0000000063706874  x23: 0x000001bf5157ca50
   x24: 0x8d6dd8b5d3e2f3f4  x25: 0xad1c74d19b891ff8  x26: 0x000001400031fb20  x27: 0x0000000000000010
   x28: 0x00000140000021a0   fp: 0x000001400031fa88   lr: 0x0000000102ee62a4
    sp: 0x000001400031fa90   pc: 0x0000000102edb2e0 cpsr: 0x20001000
   far: 0x0000000102edb2e0  esr: 0x82000007 (Instruction Abort) Translation fault

Binary Images:
       0x102ed4000 -        0x1035c7fff fyneterm (*) <91b3b3cd-eb6a-3d5e-8ef8-506e49194209> /Users/USER/*/fyneterm
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x184c29000 -        0x184c63fef libsystem_kernel.dylib (*) <a7d3c07d-0a1e-3c4c-8fba-66905e16bf99> /usr/lib/system/libsystem_kernel.dylib
       0x184b04000 -        0x184b82ff3 libsystem_c.dylib (*) <1b84a7e4-8958-330c-98b8-27d491dff69e> /usr/lib/system/libsystem_c.dylib
       0x184c64000 -        0x184c70ff3 libsystem_pthread.dylib (*) <e4debb6e-421d-33d0-9e17-77ae0e0fe4dc> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 2124
    thread_create: 0
    thread_set_state: 70

VM Region Summary:
ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)
Writable regions: Total=623.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=623.2M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           531.2M       14 
MALLOC guard page                   96K        6 
STACK GUARD                         80K        5 
Stack                             48.1M        6 
Stack Guard                       56.0M        1 
VM_ALLOCATE                        1.2G       38 
__AUTH                             717K      162 
__AUTH_CONST                      12.6M      304 
__DATA                            10.6M      294 
__DATA_CONST                      19.9M      308 
__DATA_DIRTY                       696K      105 
__FONT_DATA                        2352        1 
__LINKEDIT                       888.0M        2 
__OBJC_RO                         70.6M        1 
__OBJC_RW                         2153K        1 
__TEXT                           243.5M      320 
dyld private memory                272K        2 
mapped file                         64K        1 
shared memory                       32K        2 
===========                     =======  ======= 
TOTAL                              3.0G     1575 



-----------
Full Report
-----------

{"app_name":"fyneterm","timestamp":"2023-10-12 18:13:35.00 +0800","app_version":"","slice_uuid":"91b3b3cd-eb6a-3d5e-8ef8-506e49194209","build_version":"","platform":1,"share_with_app_devs":0,"is_first_party":1,"bug_type":"309","os_version":"macOS 14.0 (23A344)","roots_installed":0,"incident_id":"43677250-C9F2-4CA4-9EE3-A69E800A20A5","name":"fyneterm"}
{
  "uptime" : 280000,
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "coalitionID" : 8017,
  "osVersion" : {
    "train" : "macOS 14.0",
    "build" : "23A344",
    "releaseType" : "User"
  },
  "captureTime" : "2023-10-12 18:13:35.4870 +0800",
  "codeSigningMonitor" : 1,
  "incident" : "43677250-C9F2-4CA4-9EE3-A69E800A20A5",
  "pid" : 58134,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-10-12 18:13:35.0714 +0800",
  "procStartAbsTime" : 6921838627788,
  "procExitAbsTime" : 6921848544331,
  "procName" : "fyneterm",
  "procPath" : "\/Users\/USER\/*\/fyneterm",
  "parentProc" : "zsh",
  "parentPid" : 67345,
  "coalitionName" : "com.apple.Terminal",
  "crashReporterKey" : "62E55472-60A8-EA44-03CF-FFCF0C21662C",
  "responsiblePid" : 4556,
  "responsibleProc" : "Terminal",
  "codeSigningID" : "a.out",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 587334144,
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"\/tIAlB8gA9XgBwD54wMeqk6fAZTgB0D50P\/\/FwAAAAAAAAAAAAAAAA==","atPC":"kAtA+f9jMOvJBQBU\/g8f+P2DH\/j9IwDRgAAAtOEDH6riAx+qCAAAFA=="},
  "wakeTime" : 32967,
  "sleepWakeUUID" : "F95ABA04-D76F-43C4-930F-1815EE54531E",
  "sip" : "enabled",
  "vmRegionInfo" : "0x102edb2e0 is in 0x102ed4000-0x1035c8000;  bytes after start: 29408  bytes before end: 7261471\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  __TEXT                      102ed4000-1035c8000    [ 7120K] r-x\/r-x SM=COW  ...ER\/*\/fyneterm\n      __DATA_CONST                1035c8000-103708000    [ 1280K] r--\/rw- SM=COW  ...ER\/*\/fyneterm",
  "exception" : {"codes":"0x0000000000000032, 0x0000000102edb2e0","rawCodes":[50,4344099552],"type":"EXC_BAD_ACCESS","signal":"SIGKILL (Code Signature Invalid)","subtype":"UNKNOWN_0x32 at 0x0000000102edb2e0"},
  "termination" : {"flags":0,"code":2,"namespace":"CODESIGNING","indicator":"Invalid Page"},
  "ktriageinfo" : "VM - (arg = 0x0) A memory corruption was found in executable text\n",
  "vmregioninfo" : "0x102edb2e0 is in 0x102ed4000-0x1035c8000;  bytes after start: 29408  bytes before end: 7261471\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  __TEXT                      102ed4000-1035c8000    [ 7120K] r-x\/r-x SM=COW  ...ER\/*\/fyneterm\n      __DATA_CONST                1035c8000-103708000    [ 1280K] r--\/rw- SM=COW  ...ER\/*\/fyneterm",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":70,"task_for_pid":2124},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":4480352,"threadState":{"x":[{"value":4351380748,"symbolLocation":15108,"symbol":"typerel.*"},{"value":15116},{"value":15116},{"value":4351365632,"symbolLocation":0,"symbol":"runtime.types"},{"value":4352642992},{"value":4352176016,"symbolLocation":810376,"symbol":"typerel.*"},{"value":4351889120,"symbolLocation":523480,"symbol":"typerel.*"},{"value":4352176080,"symbolLocation":810440,"symbol":"typerel.*"},{"value":1},{"value":0},{"value":0},{"value":1},{"value":51},{"value":6122809232},{"value":5},{"value":1},{"value":1374392681376},{"value":1374392810256},{"value":0},{"value":0},{"value":1374392810984},{"value":1374393458448},{"value":1668311156},{"value":1921215089232},{"value":10191039807264846836},{"value":12473973511515873272},{"value":1374392810272},{"value":16},{"value":1374389543328}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4344144548},"cpsr":{"value":536875008},"fp":{"value":1374392810120},"sp":{"value":1374392810128},"esr":{"value":2181038087,"description":"(Instruction Abort) Translation fault"},"pc":{"value":4344099552,"matchesCrashFrame":1},"far":{"value":4344099552}},"queue":"com.apple.main-thread","frames":[{"imageOffset":29408,"symbol":"*\/abi.Name.Name","symbolLocation":0,"imageIndex":0},{"imageOffset":74404,"symbol":"runtime.(*itab).init","symbolLocation":388,"imageIndex":0}]},{"id":4480358,"frames":[{"imageOffset":20136,"symbol":"__semwait_signal","symbolLocation":8,"imageIndex":2},{"imageOffset":54468,"symbol":"nanosleep","symbolLocation":220,"imageIndex":3},{"imageOffset":54236,"symbol":"usleep","symbolLocation":68,"imageIndex":3},{"imageOffset":468420,"symbol":"runtime.usleep_trampoline.abi0","symbolLocation":20,"imageIndex":0},{"imageOffset":463656,"symbol":"runtime.asmcgocall.abi0","symbolLocation":200,"imageIndex":0}],"threadState":{"x":[{"value":4},{"value":0},{"value":1},{"value":1},{"value":0},{"value":5120000},{"value":10000000},{"value":2},{"value":7985145336,"symbolLocation":0,"symbol":"clock_sem"},{"value":3},{"value":17},{"value":3118626811},{"value":2043},{"value":6131215872},{"value":3120724401},{"value":433},{"value":334},{"value":8138395112},{"value":0},{"value":0},{"value":6131215824},{"value":3},{"value":0},{"value":0},{"value":0},{"value":0},{"value":4352547888,"symbolLocation":2104,"symbol":"go:funcrel.*"},{"value":1},{"value":1374389545408}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6521164996},"cpsr":{"value":2684358656},"fp":{"value":6131215808},"sp":{"value":6131215760},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6522330792},"far":{"value":5385633952}}},{"id":4480359,"frames":[{"imageOffset":20652,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":2},{"imageOffset":30204,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":4},{"imageOffset":469320,"symbol":"runtime.pthread_cond_wait_trampoline.abi0","symbolLocation":24,"imageIndex":0},{"imageOffset":463656,"symbol":"runtime.asmcgocall.abi0","symbolLocation":200,"imageIndex":0}],"threadState":{"x":[{"value":260},{"value":0},{"value":1024},{"value":0},{"value":0},{"value":160},{"value":0},{"value":0},{"value":6139636616},{"value":0},{"value":1374389752032},{"value":2},{"value":0},{"value":0},{"value":0},{"value":0},{"value":305},{"value":8138394992},{"value":0},{"value":1374389752008},{"value":1374389752072},{"value":6139637984},{"value":0},{"value":0},{"value":1024},{"value":1025},{"value":1280},{"value":0},{"value":1374389546240}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6522582524},"cpsr":{"value":1610616832},"fp":{"value":6139636736},"sp":{"value":6139636592},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6522331308},"far":{"value":6156496896}}},{"id":4480360,"frames":[{"imageOffset":20652,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":2},{"imageOffset":30204,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":4},{"imageOffset":469320,"symbol":"runtime.pthread_cond_wait_trampoline.abi0","symbolLocation":24,"imageIndex":0},{"imageOffset":463656,"symbol":"runtime.asmcgocall.abi0","symbolLocation":200,"imageIndex":0}],"threadState":{"x":[{"value":260},{"value":0},{"value":256},{"value":0},{"value":0},{"value":160},{"value":0},{"value":0},{"value":6148074376},{"value":0},{"value":1374390584160},{"value":2},{"value":0},{"value":0},{"value":0},{"value":0},{"value":305},{"value":8138394992},{"value":0},{"value":1374390584136},{"value":1374390584200},{"value":6148075744},{"value":0},{"value":0},{"value":256},{"value":257},{"value":512},{"value":18446744073709551520},{"value":1374390591904}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6522582524},"cpsr":{"value":1610616832},"fp":{"value":6148074496},"sp":{"value":6148074352},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6522331308},"far":{"value":6156496896}}},{"id":4480361,"frames":[{"imageOffset":20652,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":2},{"imageOffset":30204,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":4},{"imageOffset":469320,"symbol":"runtime.pthread_cond_wait_trampoline.abi0","symbolLocation":24,"imageIndex":0},{"imageOffset":463656,"symbol":"runtime.asmcgocall.abi0","symbolLocation":200,"imageIndex":0}],"threadState":{"x":[{"value":260},{"value":0},{"value":0},{"value":0},{"value":0},{"value":160},{"value":0},{"value":0},{"value":6156495800},{"value":0},{"value":1374389753184},{"value":2},{"value":0},{"value":0},{"value":0},{"value":0},{"value":305},{"value":8138394992},{"value":0},{"value":1374389753160},{"value":1374389753224},{"value":6156497120},{"value":0},{"value":0},{"value":0},{"value":1},{"value":256},{"value":32},{"value":1374389548320}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6522582524},"cpsr":{"value":1610616832},"fp":{"value":6156495920},"sp":{"value":6156495776},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6522331308},"far":{"value":6148075520}}},{"id":4480362,"frames":[{"imageOffset":20652,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":2},{"imageOffset":30204,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":4},{"imageOffset":469320,"symbol":"runtime.pthread_cond_wait_trampoline.abi0","symbolLocation":24,"imageIndex":0},{"imageOffset":463656,"symbol":"runtime.asmcgocall.abi0","symbolLocation":200,"imageIndex":0}],"threadState":{"x":[{"value":260},{"value":0},{"value":0},{"value":0},{"value":0},{"value":160},{"value":0},{"value":0},{"value":6164917512},{"value":0},{"value":1374391124832},{"value":2},{"value":0},{"value":0},{"value":0},{"value":0},{"value":305},{"value":8138394992},{"value":0},{"value":1374391124808},{"value":1374391124872},{"value":6164918496},{"value":0},{"value":0},{"value":0},{"value":1},{"value":256},{"value":18446744073709551520},{"value":1374391132576}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6522582524},"cpsr":{"value":1610616832},"fp":{"value":6164917632},"sp":{"value":6164917488},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6522331308},"far":{"value":6156496896}}}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4344070144,
    "size" : 7290880,
    "uuid" : "91b3b3cd-eb6a-3d5e-8ef8-506e49194209",
    "path" : "\/Users\/USER\/*\/fyneterm",
    "name" : "fyneterm"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6522310656,
    "size" : 241648,
    "uuid" : "a7d3c07d-0a1e-3c4c-8fba-66905e16bf99",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6521110528,
    "size" : 520180,
    "uuid" : "1b84a7e4-8958-330c-98b8-27d491dff69e",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6522552320,
    "size" : 53236,
    "uuid" : "e4debb6e-421d-33d0-9e17-77ae0e0fe4dc",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  }
],
  "sharedCache" : {
  "base" : 6518161408,
  "size" : 4012523520,
  "uuid" : "7906534c-5d2b-3ba8-b9c6-93a5cf1b7b50"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)\nWritable regions: Total=623.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=623.2M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           531.2M       14 \nMALLOC guard page                   96K        6 \nSTACK GUARD                         80K        5 \nStack                             48.1M        6 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                        1.2G       38 \n__AUTH                             717K      162 \n__AUTH_CONST                      12.6M      304 \n__DATA                            10.6M      294 \n__DATA_CONST                      19.9M      308 \n__DATA_DIRTY                       696K      105 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       888.0M        2 \n__OBJC_RO                         70.6M        1 \n__OBJC_RW                         2153K        1 \n__TEXT                           243.5M      320 \ndyld private memory                272K        2 \nmapped file                         64K        1 \nshared memory                       32K        2 \n===========                     =======  ======= \nTOTAL                              3.0G     1575 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "7a7af31d75cd6f4e20d89d16823634ba5d10bb31",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "639124e81d92412bfb4880b3",
      "factorPackIds" : {

      },
      "deploymentId" : 240000012
    },
    {
      "rolloutId" : "60f8ddccefea4203d95cbeef",
      "factorPackIds" : {

      },
      "deploymentId" : 240000025
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "6dd670af-0633-45e4-ae5f-122ae4df02be",
      "experimentId" : "64406ba83deb637ac8a04419",
      "deploymentId" : 900000017
    }
  ]
}
}

```

**Comment by bamcop** [comment]
[systray](github.com/energye/systray) library also has similar problems

**Comment by andydotxyz** [comment]
The Go team / triage have marked this as an issue with Apple macOS and not an issue with Go. I am not sure what we can do as a result...

**Comment by toaster** [comment]
@andydotxyz is there a reference to the Go team/triage’s decision?

**Comment by andydotxyz** [comment]
The one I meant to link to (sorry for the delay!) was:

https://github.com/golang/go/issues/63368

Likely the code signing issue was this one:

https://github.com/golang/go/issues/63997

Closing this as both were resolved / closed upstream.

**Comment by romanitalian** [comment]
This issue is not resolved. Fyne should cover this case and provide a way to make the Signature Valid.

**Comment by andydotxyz** [comment]
There isn't much we can do to fix what happens in the compiler. Thankfully, despite statements from triage that it was not a Go issue, people have reported that this is fixed by upgrading Go. Try moving to 1.23.x and you should see that it is fixed.
