### ISSUE TITLE
Interface of widget.TextSegment has been broken on develop

### ISSUE THREAD

**Issue by codesoap** [fyne-io/fyne#4636]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

With fyne 2.4.3, I was able to instantiate `widget.TextSegment` using a struct literal, without naming the fields of the struct. Due to the new, hidden `parent` field (from 5e419b2a7d50531d608b41e8a49ccdcafd74d4b1), this no longer works. I now get this compiler error:

> too few values in struct literal of type "fyne.io/fyne/v2/widget".TextSegment

### How to reproduce

Simply try to instantiate `widget.TextSegment` using a struct literal, without naming the fields. This was possible with fyne 2.4.3, but is not possible on the `develop` branch.

### Example code

```go
myText := widget.TextSegment{widget.RichTextStyle{}, "Hello, world"}
```

### Fyne version

develop (after commit 5e419b2a7d50531d608b41e8a49ccdcafd74d4b1)

### Go compiler version

1.22.0

### Operating system and version

MX Linux, I believe version 21; it's basically Debian

### Additional Information

This was news to me, but apparently it's impossible to use struct literals for structs with unexported fields, if the fields are not named. If the fields are named, it still works:

```go
myText := widget.TextSegment{Style: widget.RichTextStyle{}, Text: "Hello, world"}
```

Because existing code could already use struct literals with `widget.TextSegment`, I consider this a breaking change.

**Comment by Jacalz** [comment]
This is not a breaking change because you are supposed to name the fields you set. Many code analysers even give you an error when you have unnamed strict parameters. If this was considered a breaking change, we would never be able to improve the types without introducing a new type i.e. everything would be a breaking change. I will close this as not being an issue.

**Comment by codesoap** [comment]
I see. Thanks for evaluating.

**Comment by Jacalz** [comment]
No worries. Thanks for keeping a close eye on the codebase

**Comment by andydotxyz** [comment]
The OP is right it does feel like something broke (though I agree its not a breaking change).
What we may need to do however is to ensure any usage of struct literals in our codebase all use named fields ;).

**Comment by andydotxyz** [comment]
Thanks so much for that. We should fix them anyway, as @Jacalz said it's something linters complain about so our docs should this best practice!

**Comment by andydotxyz** [comment]
Those instances should be fixed now :)

**Comment by codesoap** [comment]
@andydotxyz `canvas/circle.md` and `canvas/raster.md` look good to me. In `_gen/genlayouts.go` I still see the "old" style in [line 29](https://github.com/fyne-io/docs.fyne.io/blob/7552db32e6adb8cf9d542972efc720b786d528a9/_gen/genlayouts.go#L29) and [line 32](https://github.com/fyne-io/docs.fyne.io/blob/7552db32e6adb8cf9d542972efc720b786d528a9/_gen/genlayouts.go#L32).

**Comment by andydotxyz** [comment]
Ah yes. This does not actually print to the docs site, just generates images.
But I have fixed it for good measure.
