### ISSUE TITLE
Window periodically misdraws into a smaller area on startup

### ISSUE THREAD

**Issue by dweymouth** [fyne-io/fyne#4964]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Seems to only happen on Linux, and on Ubuntu 24.04 it happens up to 50% of the time, much more often than 22.04, according to Supersonic user reports. When this happens the window canvas also isn't responsive to mouse events at all.

I'm *really* tempted to mark this as a blocker since it is a **huge** negative to the UX of Fyne apps on Linux, at least on whatever distros are affected. Though manually resizing the window does fix it when it gets in this state.

### How to reproduce

Launch a Fyne app on Ubuntu 24.04 until it shows up misdrawn

### Screenshots

Screenshot from a Supersonic user:

![image](https://github.com/fyne-io/fyne/assets/5303666/f8ca742f-7cf7-4168-ba7c-4c00d083b6bd)

### Example code

n/a

### Fyne version

develop

### Go compiler version

n/a

### Operating system and version

Linux (especially Ubuntu 24.04)

**Comment by dweymouth** [comment]
I'll just share my *incredibly* hacky workaround here (which replaced my previous, ineffective attempt at a workaround) in case anyone else is affected: https://github.com/dweymouth/supersonic/commit/2736fe9955006444eb3bb58181b5e6b1bee68c61

I send a resize event through X11 shortly after the window is shown, so that if it ends up in the misdrawn state it will be forced out of it

**Comment by p4k1tz** [comment]
I can also confirm this is happening on Windows as well. Not created a workaround yet.

**Comment by dweymouth** [comment]
This also happens with native Wayland builds (`go build -tags wayland`) according to user reports

**Comment by dweymouth** [comment]
marking this as blocker since it happens quite frequently to a lot of users of Fyne apps, and apparently not just on Linux either

**Comment by dweymouth** [comment]
System info from an affected user. They seem to see the issue on 10-20% of startups (and all of my attempted workarounds in app code have been at best partially effective) 

![image](https://github.com/user-attachments/assets/f4fe8708-aac0-4016-b008-7416153c49f2)

**Comment by and3rson** [comment]
I'm experiencing the same issue.
In my setup, I have AdaptiveGrid with 2 lists inside.
List items randomly appear too narrow.
Reproducible in both wayland & X.

**Comment by andydotxyz** [comment]
That may be an unrelated issue... If you are extending a widget and don't do it currently the renderer can fail to get Resize right - did you call `ExtendBaseWidget`?

**Comment by and3rson** [comment]
@andydotxyz yes, I can reproduce it with and without ExtendBaseWidget

**Comment by andydotxyz** [comment]
Your code is creating two lists (or two list pointers, depending on the setup) - this will confuse things.
Try this instead:

```go
type myList struct {
    widget.List
    // same behavior when extending `widget.List`
}

// ...
l := myList{}
l.Bind(...)
l.ExtendBaseWidget(l)
```

If you call a widget constructor inside your widget constructor then (to simplify a complex problem) the UI does not know which of the two you are rendering. Instead instantiate your struct with the parent widget embedded directly (not with a pointer) and then configure it using the inherited methods or fields.

**Comment by hkparker** [comment]
@dweymouth for what it's worth I wasn't able to reproduce the hacky fix in my environment (X.Org X Server 1.21.1.14).  I used it to resize to the same dimensions I started with at least, and had the same half-sized startup pretty frequently.

**Comment by andydotxyz** [comment]
Resizing to the same size will be a no-op because the window layout won't be called.

**Comment by hkparker** [comment]
I just tried adding 1 to both the width and height with no change, still am able to reproduce.  It looked like the example didn't change the size which is why that was my first try.  I had to change one line of the C though because my compiler was complaining about an incompatible pointer type on the windows argument to `find_windows_by_pid`, so actually that might be my issue.

**Comment by andydotxyz** [comment]
One last test - create the window larger, and then resize it down in the workaround delay - I think I also saw a resize up not make a difference on one test app...

**Comment by andydotxyz** [comment]
We are going to try and resolve this in 2.5.x but there is a suspicion it gets resolved with 2.6.0 updates which we are trying to bring forward...

**Comment by hkparker** [comment]
Good catch @andydotxyz, per our discussion elsewhere I tried to avoid C and just added

```go
go func() {
    time.Sleep(100 * time.Millisecond)
    mainWindow.Resize(fyne.NewSize(defaultWidth, defaultHeight-1))
}()
```

and that seems to be an effective (and cross platform, presumably) workaround

**Comment by hkparker** [comment]
I spoke too soon, while this was an improvement I'm still seeing this issue, just less frequently.  I suspect sometimes 100ms isn't enough, but I'm not confident what the root cause is.

**Comment by andydotxyz** [comment]
It would be interesting to test this against `develop` now that we have begun the threading changes...

**Comment by andydotxyz** [comment]
It seems to me a different issue (but with similar outcome). The former was a race condition for any Linux systems, but the latter maybe more reliably produced but only on Wayland.

That said I have not been able to recreate it using Weston.

**Comment by dweymouth** [comment]
OK in further testing it does seem to be resolved on wayland for me, somewhere in between the first alpha for 2.6 and the final release something must have fixed it. I still have #5357 but we can finally close this one out.
