### ISSUE TITLE
wasm exit after paste a unicode to input entry

### ISSUE THREAD

**Issue by lynic** [fyne-io/fyne#5370]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

web stop working after pasting a unicode in input box.
I've already used a custom theme with my language support.

### How to reproduce

Add a input box , either NewEntry() or NewMultiLineEntry()
Start it with `fyne serve`
Copy and paste unicode in input box
Then it stop working

### Screenshots

![image](https://github.com/user-attachments/assets/a65d0377-7313-4038-b4a5-ee3ed0188df0)

### Example code

```go
	myApp := app.New()
	myApp.Settings().SetTheme(&MyTheme{})
	myWindow := myApp.NewWindow("app")

	input := widget.NewMultiLineEntry()
	input.SetPlaceHolder("在这里输入你的消息...")
	input.SetText("")
```

### Fyne version

2.5.3

### Go compiler version

1.22.2

### Operating system and version

Linux

**Comment by andydotxyz** [comment]
The log makes it look not like unicode but that somehow the clipboard is being called on a nil window.
This will be resolved in v2.6.0 because we are moving to app-wide clipboard

**Comment by andydotxyz** [comment]
Fixed on `release/v2.5.x` branch if you want the fix :)

**Comment by lynic** [comment]
It would be great if fix can be landed on 2.5.x , thanks!

**Comment by lynic** [comment]
I tried with 2.5.x branch, seems paste from clipboard still crashed.
 
<img width="1108" alt="image" src="https://github.com/user-attachments/assets/d9fb9584-c146-412f-bb62-54e757bab7e8" />

**Comment by andydotxyz** [comment]
Believe it or not that is a different crash. This time it may be specific to what you pasted or the app you are running - I tested the fix in my app and it works fine.

Can you give more detailed steps to replicate please?

**Comment by andydotxyz** [comment]
> This probably related how we access the service.
> If I access it via "http://localhost:8080" , and paste the url in input box, it works fine.
> But if I open it using DHCP IP "http://172.20.0.170:8080", and paste the url in input box, it crashed.

That is interesting, but I cannot replicate with the same difference at this end.
Can you please provide more info about the browser so we can replicate your report.
