### ISSUE TITLE
Web app via `fyne serve` blinks and closes, same app under web server runs OK

### ISSUE THREAD

**Issue by bobhy** [fyne-io/fyne#5705]
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [x] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

Given the app below, if I serve via `fyne serve`, it exits due to (I think) a file open error.  If I serve same app via `fyne package` and `python -m http.server`, it works OK (but logs a 'not implemented in js' error trying to open user theme `/data/theme.json`).

So the problem is why `fyne serve` didn't work when packaging + local server did.  
This isn't a blocker for me, I can continue using the package + local server for now.
 
But the theme file not found error from the packaged scenario is curious.  Questions:
1. Did  `fyne serve` encounter the same error and just panic too soon?  
I can't  tell from the stack trace, included below for your amusement.
2.  code [here](https://github.com/fyne-io/fyne/blob/a276e577964430e9ee2eadbc84f16f6a87a29fd9/app/settings.go#L135-L138)
 makes me think the the code is expecting "file not found" (when opening theme file),  but it actually encountered "not implemented in js".  Is this a known issue to be fixed later?  It's just an extra log messasge, I get the default theme anyway.

### How to reproduce

1.` cd <sourceDir>`
2. `fyne serve`
3. open browser, dev console, then browse to localhost:8080

Expect:  App should open
Observe: brief flash (might be loading wasm spinner?), then blank
In dev console, this console log:

```text
wasm_exec.js:20 panic: syscall/js: Value.Call: property open is not a function, got undefined
writeConsole @ wasm_exec.js:20
runtime.wasmWrite @ wasm_exec.js:215
$runtime.wasmWrite @ GS_Web_App.wasm:0xa40f6
$runtime.write1 @ GS_Web_App.wasm:0xa407f
$runtime.write @ GS_Web_App.wasm:0x134f81
$runtime.writeErrData @ GS_Web_App.wasm:0xd74ec
$runtime.gwrite @ GS_Web_App.wasm:0xad130
$runtime.printstring @ GS_Web_App.wasm:0xae180
$runtime.printnl @ GS_Web_App.wasm:0xad2ba
$runtime.printpanics @ GS_Web_App.wasm:0xa7c41
$runtime.fatalpanic.func1 @ GS_Web_App.wasm:0xaa453
$runtime.systemstack @ GS_Web_App.wasm:0x136dad
$runtime.fatalpanic @ GS_Web_App.wasm:0xaa24d
$runtime.gopanic @ GS_Web_App.wasm:0x129c2e
$syscall_js.Value.Call @ GS_Web_App.wasm:0x16df4c
$syscall.fsCall @ GS_Web_App.wasm:0x18050d
$syscall.Open @ GS_Web_App.wasm:0x17a24b
$os.openFileNolog @ GS_Web_App.wasm:0x27649e
$os.OpenFile @ GS_Web_App.wasm:0x272159
$os.ReadFile @ GS_Web_App.wasm:0x27361e
$fyne.io_fyne_v2.LoadResourceFromPath @ GS_Web_App.wasm:0x7c48c3
$fyne.io_fyne_v2_app.__settings_.loadSystemTheme @ GS_Web_App.wasm:0x10ad81b
$fyne.io_fyne_v2_app.__settings_.setupTheme @ GS_Web_App.wasm:0x10ae159
$fyne.io_fyne_v2_app.newAppWithDriver @ GS_Web_App.wasm:0x10a58ee
$wasm_pc_f_loop @ GS_Web_App.wasm:0x13965b
$wasm_export_resume @ GS_Web_App.wasm:0x13974e
_resume @ wasm_exec.js:519
(anonymous) @ wasm_exec.js:530
--- clip ---
```

4. `fyne build -os web`
5. `cd wasm`
6. `python  -m http.server`
7. open browser, dev console, then browse to localhost:8000

Observe: app opens and runs as expected
In dev console, this log:
```text
2025/04/29 10:15:38 Fyne error:  Failed to load user theme file: /data/theme.json
wasm_exec.js:22 
2025/04/29 10:15:38   Cause: open /data/theme.json: not implemented on js
wasm_exec.js:22 
2025/04/29 10:15:38   At: /home/bobhy/go/pkg/mod/fyne.io/fyne/v2@v2.6.0/app/settings.go:136
wasm_exec.js:22 
2025/04/29 10:15:38 Fyne error:  Failed to load user theme file: /data/theme.json
wasm_exec.js:22 
2025/04/29 10:15:38   Cause: open /data/theme.json: not implemented on js
wasm_exec.js:22 
2025/04/29 10:15:38   At: /home/bobhy/go/pkg/mod/fyne.io/fyne/v2@v2.6.0/theme/theme.go:368
```

### Example code

Sample program:
```go
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func makeUI() (*widget.Label, *widget.Entry) {
	out := widget.NewLabel("Hello world!")
	in := widget.NewEntry()

	in.OnChanged = func(content string) {
		out.SetText("Hello " + content + "!")
	}
	return out, in
}

func main() {
	a := app.New()
	w := a.NewWindow("Hello Person")

	w.SetContent(container.NewVBox(makeUI()))
	w.ShowAndRun()
}
```

### Fyne version

fyne cli version: v1.6.1 fyne library version: v2.6.0

### Go compiler version

go1.24.2 linux/amd64

### Operating system and version

ubuntu oracular

**Comment by andydotxyz** [comment]
I don't think we should close this - if a mainstream browser is causing the code to panic somehow...

**Comment by bobhy** [comment]
Reopening.  I can confirm the `fyne serve` failure happens with Brave but not with Chrome or Edge browsers on my system (ubuntu oracular).

Can anyone make useful sense out of the panic crash stack in Dev Console?  Or say what additional testing I could do to help debug?

**Comment by andydotxyz** [comment]
Just for clarity - when it worked with the Python server was that also using Brave?

**Comment by bobhy** [comment]
Correct,  python server works on all browsers.

**Comment by andydotxyz** [comment]
The plot thickens then.
I also tried on Brave Browser (macOS) and cannot replicate the problem.

Perhaps if anyone else here is using Brave they could check too?

**Comment by bobhy** [comment]
What debugging info could I provide that would be helpful?  I certainly
could have a weird config, though I didn't intend to create one...

**Comment by cognusion** [comment]
Oddly I have the same symptom (Brave on Windows and Linux tested). The "loading" screen comes up, and after the WASM is downloaded it blinks off. Tapping anywhere in the browser window brings it back. This also occurs when serving the same WASM files via Apache HTTPD, with the same browsers. Firefox does not appear to have the issue.

**Comment by andydotxyz** [comment]
Try to give that patch a go - I cannot replicate here, but logically that should fix the issue...

**Comment by cognusion** [comment]
The errors in the console changed, but the symptoms are still the same. 

2025/08/23 22:34:44 Fyne error:  Failed to load user theme file: /data/theme.json
2025/08/23 22:34:44   Cause: open /data/theme.json: not implemented on js
2025/08/23 22:34:44   At: <..snip..>/fyne/theme/theme.go:368

**Comment by andydotxyz** [comment]
I belive this was resolved in the linked PR
