### ISSUE TITLE
TextGrid is glitchy when calling SetText on a scrolled container.

### ISSUE THREAD

**Issue by redawl** [fyne-io/fyne#5762]
### Checklist

- [x] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [x] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

When calling SetText on a scrolled TextGrid, if the new next doesn't reach down as far as the previous text, there are visual glitches, like the text not appearing, or appearing only partially.

### How to reproduce

1. Run example code
2. Click button twice
3. Scroll down a ways
4. Click button again
5. Notice that new text doesn't show until the TextGrid is touched.

### Example code

```go
package main

import (
        "strconv"
        "strings"

        "fyne.io/fyne/v2"
        "fyne.io/fyne/v2/app"
        "fyne.io/fyne/v2/container"
        "fyne.io/fyne/v2/widget"
)

func multiplyString(str string, i int) string {
        builder := strings.Builder{}
        inc := i
        for inc > 0 {
                builder.WriteString(strconv.Itoa(i - inc))
                builder.WriteString(": ")
                builder.WriteString(str)
                builder.WriteByte('\n')
                inc--
        }

        return builder.String()
}

func main() {
        a := app.New()
        w := a.NewWindow("Test")
        text := "Example text"
        toggle := false

        textGridWrapper := &widget.TextGrid{
                Scroll: fyne.ScrollBoth,
        }

        button := widget.NewButton("Click me!", func() {
                if toggle {
                        textGridWrapper.SetText(multiplyString(text, 10000))
                } else {
                        textGridWrapper.SetText(multiplyString(text, 50))
                }
                toggle = !toggle
        })

        textGridWrapper.SetText(text)
        layout := container.NewBorder(nil, nil, nil, button, textGridWrapper)

        w.SetContent(layout)
        w.ShowAndRun()
}
```

### Fyne version

develop

### Go compiler version

1.24.3

### Operating system and version

Gentoo

**Comment by andydotxyz** [comment]
I feel like this has been resolved recently but cannot find the PR - can you recall / verify @redawl ?

**Comment by redawl** [comment]
This one is still an issue. I am working on a fix.
The underlying problem is that the internal scroll needs to scroll up to the new bottom of the textgrid if the new text is shorter than the previous scroll location.

**Comment by andydotxyz** [comment]
Ah that makes sense, thanks so much !
