### ISSUE TITLE
Ubuntu 18 gl._Cfunc_glowViewport crash

### ISSUE THREAD

**Issue by xgreenx** [fyne-io/fyne#640]
### Describe the bug:
I show a small window with check boxes and often I can get crash during `ShowAndRun`. I don't know why, because another part of code with ImageWidget doesn't have problems.

![image](https://user-images.githubusercontent.com/18346821/73541648-a8902680-443b-11ea-98ac-32b483575d71.png)

I didn't have problems on Ubuntu 16.

### Screenshots:
```
goroutine 727 [syscall, locked to thread]:
runtime.cgocall(0xc65c30, 0xc000521650, 0x0)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000521620 sp=0xc0005215e8 pc=0x433f4b
github.com/go-gl/gl/v3.2-core/gl._Cfunc_glowViewport(0x7f21960b6580, 0x0, 0x960000048f)
	_cgo_gotypes.go:23605 +0x45 fp=0xc000521650 sp=0xc000521620 pc=0xa2d805
github.com/go-gl/gl/v3.2-core/gl.Viewport(...)
	/home/newman/work/go/pkg/mod/github.com/go-gl/gl@v0.0.0-20190320180904-bf2b1f2f34d7/v3.2-core/gl/package.go:13085
fyne.io/fyne/internal/painter/gl.(*glPainter).SetOutputSize(0xc0005670b0, 0x48f, 0x96)
	/home/newman/work/go/pkg/mod/github.com/xgreenx/fyne@v1.2.0-beta1.0.20200130101155-2d09977f181c/internal/painter/gl/gl_core.go:70 +0x48 fp=0xc000521678 sp=0xc000521650 pc=0xa4e4d8
fyne.io/fyne/internal/driver/glfw.(*window).frameSized(0xc0005a0000, 0xc00045b200, 0x48f, 0x96)
	/home/newman/work/go/pkg/mod/github.com/xgreenx/fyne@v1.2.0-beta1.0.20200130101155-2d09977f181c/internal/driver/glfw/window.go:482 +0xca fp=0xc0005216a0 sp=0xc000521678 pc=0xa54c9a
fyne.io/fyne/internal/driver/glfw.(*window).frameSized-fm(0xc00045b200, 0x48f, 0x96)
	/home/newman/work/go/pkg/mod/github.com/xgreenx/fyne@v1.2.0-beta1.0.20200130101155-2d09977f181c/internal/driver/glfw/window.go:474 +0x48 fp=0xc0005216d0 sp=0xc0005216a0 pc=0xa5ae38
github.com/go-gl/glfw/v3.2/glfw.goFramebufferSizeCB(0x7f213c022840, 0x960000048f)
	/home/newman/work/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20181213070059-819e8ce5125f/v3.2/glfw/window.go:191 +0x61 fp=0xc0005216f8 sp=0xc0005216d0 pc=0x9750b1
github.com/go-gl/glfw/v3.2/glfw._cgoexpwrap_cd92c578db63_goFramebufferSizeCB(0x7f213c022840, 0x960000048f)
	_cgo_gotypes.go:2226 +0x3b fp=0xc000521718 sp=0xc0005216f8 pc=0x971bfb
runtime.call32(0x0, 0x7f213bffe260, 0x7f213bffe2f0, 0x10)
	/usr/local/go/src/runtime/asm_amd64.s:539 +0x3b fp=0xc000521748 sp=0xc000521718 pc=0x48acbb
runtime.cgocallbackg1(0x0)
	/usr/local/go/src/runtime/cgocall.go:314 +0x1b7 fp=0xc000521830 sp=0xc000521748 pc=0x4342f7
runtime.cgocallbackg(0x0)
	/usr/local/go/src/runtime/cgocall.go:191 +0xc1 fp=0xc000521898 sp=0xc000521830 pc=0x4340a1
runtime.cgocallback_gofunc(0x433f6f, 0xc48da0, 0xc000521928, 0xc00049c600)
	/usr/local/go/src/runtime/asm_amd64.s:793 +0x9b fp=0xc0005218b8 sp=0xc000521898 pc=0x48c28b
runtime.asmcgocall(0xc48da0, 0xc000521928)
	/usr/local/go/src/runtime/asm_amd64.s:640 +0x42 fp=0xc0005218c0 sp=0xc0005218b8 pc=0x48c122
runtime.cgocall(0xc48da0, 0xc000521928, 0xc00049c738)
	/usr/local/go/src/runtime/cgocall.go:131 +0x7f fp=0xc0005218f8 sp=0xc0005218c0 pc=0x433f6f
github.com/go-gl/glfw/v3.2/glfw._Cfunc_glfwPollEvents()
	_cgo_gotypes.go:1197 +0x41 fp=0xc000521928 sp=0xc0005218f8 pc=0x96f191
github.com/go-gl/glfw/v3.2/glfw.PollEvents()
	/home/newman/work/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20181213070059-819e8ce5125f/v3.2/glfw/window.go:777 +0x22 fp=0xc000521960 sp=0xc000521928 pc=0x977112
fyne.io/fyne/internal/driver/glfw.(*gLDriver).runGL(0xc000566f60)
	/home/newman/work/go/pkg/mod/github.com/xgreenx/fyne@v1.2.0-beta1.0.20200130101155-2d09977f181c/internal/driver/glfw/loop.go:84 +0x1ff fp=0xc000521ae0 sp=0xc000521960 pc=0xa5255f
fyne.io/fyne/internal/driver/glfw.(*gLDriver).Run(0xc000566f60)
	/home/newman/work/go/pkg/mod/github.com/xgreenx/fyne@v1.2.0-beta1.0.20200130101155-2d09977f181c/internal/driver/glfw/driver.go:69 +0x2b fp=0xc000521af8 sp=0xc000521ae0 pc=0xa51fcb
fyne.io/fyne/internal/driver/glfw.(*window).ShowAndRun(0xc0005a0000)
	/home/newman/work/go/pkg/mod/github.com/xgreenx/fyne@v1.2.0-beta1.0.20200130101155-2d09977f181c/internal/driver/glfw/window.go:380 +0x57 fp=0xc000521b20 sp=0xc000521af8 pc=0xa545f7
github.com/xgreenx/desktop-sharing/src/sharingnode.GUIAllower.Allow(0x0, 0x0, 0x0, 0xc0001e5110, 0xc0005961c0, 0x0, 0xdbfc00, 0x0, 0x0)
	/home/newman/Downloads/desktop-sharing/src/sharingnode/allower.go:106 +0x92b fp=0xc000521ca0 sp=0xc000521b20 pc=0xc2e33b
```

Another crash with glfw._Cfunc_glfwCreateWindow

```

goroutine 2772 [syscall]:
runtime.cgocall(0xc48c70, 0xc00051d910, 0x43d6b8)
	/usr/lib/go-1.13/src/runtime/cgocall.go:128 +0x5b fp=0xc00051d8e0 sp=0xc00051d8a8 pc=0x433e9b
github.com/go-gl/glfw/v3.2/glfw._Cfunc_glfwCreateWindow(0xa0000000a, 0x7f688438c520, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:550 +0x4e fp=0xc00051d910 sp=0xc00051d8e0 pc=0x96d8ae
github.com/go-gl/glfw/v3.2/glfw.CreateWindow.func2(0xa, 0xa, 0x7f688438c520, 0x0, 0x0, 0xc001c0db80)
	/home/green/pkg/mod/github.com/go-gl/glfw@v0.0.0-20181213070059-819e8ce5125f/v3.2/glfw/window.go:286 +0xab fp=0xc00051d948 sp=0xc00051d910 pc=0x97847b
github.com/go-gl/glfw/v3.2/glfw.CreateWindow(0xa, 0xa, 0xe9c087, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/green/pkg/mod/github.com/go-gl/glfw@v0.0.0-20181213070059-819e8ce5125f/v3.2/glfw/window.go:286 +0xff fp=0xc00051d9e8 sp=0xc00051d948 pc=0x974f1f
fyne.io/fyne/internal/driver/glfw.(*gLDriver).CreateWindow.func1()
	/home/green/pkg/mod/github.com/xgreenx/fyne@v1.2.0-beta1.0.20200130170943-60a8f3b36494/internal/driver/glfw/window.go:1148 +0x9d fp=0xc00051da70 sp=0xc00051d9e8 pc=0xa5b0ed
fyne.io/fyne/internal/driver/glfw.runOnMain(0xc000314cf0)
	/home/green/pkg/mod/github.com/xgreenx/fyne@v1.2.0-beta1.0.20200130170943-60a8f3b36494/internal/driver/glfw/loop.go:41 +0xab fp=0xc00051dab0 sp=0xc00051da70 pc=0xa5324b
fyne.io/fyne/internal/driver/glfw.(*gLDriver).CreateWindow(0xc000314b70, 0xe9c087, 0xc, 0xc00008e5a0, 0xc000314b70)
	/home/green/pkg/mod/github.com/xgreenx/fyne@v1.2.0-beta1.0.20200130170943-60a8f3b36494/internal/driver/glfw/window.go:1139 +0x99 fp=0xc00051dad8 sp=0xc00051dab0 pc=0xa593f9
fyne.io/fyne/app.(*fyneApp).NewWindow(0xc00008e5a0, 0xe9c087, 0xc, 0x203000, 0x203000)
	/home/green/pkg/mod/github.com/xgreenx/fyne@v1.2.0-beta1.0.20200130170943-60a8f3b36494/app/app.go:43 +0x47 fp=0xc00051db10 sp=0xc00051dad8 pc=0xa5c377
github.com/xgreenx/desktop-sharing/src/sharingnode.GUIAllower.Allow(0x0, 0x0, 0x0, 0xc000225110, 0xc00000eb80, 0x0, 0xdbfb00, 0x0, 0x0)
	/home/green/src/github.com/xgreenx/desktop-sharing/src/sharingnode/allower.go:66 +0x140 fp=0xc00051dca0 sp=0xc00051db10 pc=0xc2d890
```

### Device (please complete the following information):
 - OS: Ubuntu
 - Version: 18
 - Go version: go version go1.13 linux/amd64
 - Fyne version: 1.2.2 (but old version too)

**Comment by andydotxyz** [comment]
Can you first please try updating to v1.2.2? Some issues in this area have been resolved recently.

**Comment by xgreenx** [comment]
It is already 1.2.2, I did fork at 1.2.0-beta before. When I got crash I rebased to a  new version 1.2.2, but goland still show it like 1.2.0-beta(I checked code) and crash still exist. Also a new version has problems with drawing of this code:
If you move the mouse around each check box(You need to highlight/unhighlight  them) many time, check boxes can disappear(Button also has the same problem).  This bug I can reproduce on Ubunut 16 and 18. (All was fine before 1.2.2 update)

**Comment by andydotxyz** [comment]
The log that you have provided above is v1.2.0. It looks like you are using modules, perhaps you can share your go.mod file?

**Comment by andydotxyz** [comment]
We have not seen items disappear - can you please open a new issue with code to reproduce the issue?

**Comment by xgreenx** [comment]
> The log that you have provided above is v1.2.0. It looks like you are using modules, perhaps you can share your go.mod file?

I forked you when you had release 1.2.0-beta. 
https://github.com/xgreenx/fyne

And golang shows the latest release tag. But I rebased master to your master after release 1.2.2, so the code is actual=) I checked that several times
https://github.com/fyne-io/fyne/compare/master...xgreenx:master


> We have not seen items disappear - can you please open a new issue with code to reproduce the issue?

https://github.com/fyne-io/fyne/issues/641

**Comment by andydotxyz** [comment]
Thanks for the confirmation.
Is it possible to recreate the issue with vanilla Fyne code? Looking at your example you are accessing internals that we don’t support, so it’s hard to get stuck in here...

Also why not use our Window.SetOnClosed() which is supported?

**Comment by xgreenx** [comment]
I close this bug, because i run this code in not main thread. I thought that if run application in goroutine and this goroutine own it, all must be ok. But this code works fine in main thread.

**Comment by andydotxyz** [comment]
Ah yes sorry, Run() or ShowAndRun() must execute from main()
